version: "3"
services:
  bird_ai:
    image: ${REPOSITORY}:latest # Make sure your Docker image has this name.
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:7.0.1
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
