version: "3"
services:
  bird_ai:
    image: ${REPOSITORY}:1.0.0
    #image: bird_ai # for running local build aka "make build"
    container_name: bird_ai
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - compose/.env
      - secret/.env
    restart: unless-stopped
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:7.0.1
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db

  mongo_setup:
    container_name: mongo_setup
    build:
      context: ./mongo-setup
      dockerfile: Dockerfile
    depends_on:
      - mongodb

volumes:
  dbdata: