basePath: /
definitions:
  models.User:
    properties:
      _id:
        type: string
      username:
        type: string
    type: object
  users.ResponseHTTP:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
host: 127.0.0.1:3300
info:
  contact:
    email: ??
    name: Tovah Parnes
  description: A server for BirdAI API, for managing users, admin, birds, posts and
    more.
  license:
    name: MIT License
    url: https://opensource.org/license/mit/
  termsOfService: http://swagger.io/terms/
  title: BirdAI API
  version: "2.0"
paths:
  /users/:
    post:
      consumes:
      - application/json
      description: Create User
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/users.ResponseHTTP'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/users.ResponseHTTP'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/users.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/users.ResponseHTTP'
      summary: Create user
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/users.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.User'
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/users.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/users.ResponseHTTP'
      summary: Get user by ID
      tags:
      - users
  /users/me:
    post:
      consumes:
      - application/json
      description: Get current user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/users.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.User'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/users.ResponseHTTP'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/users.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/users.ResponseHTTP'
      summary: Get current user
      tags:
      - users
<<<<<<< HEAD
=======
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/users.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.User'
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/users.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/users.ResponseHTTP'
      summary: Get user by ID
      tags:
      - users
>>>>>>> 9e910e6 (Implementing endpoint structure)
  /users/set:{set}:
    get:
      consumes:
      - application/json
      description: Get set of all users
      parameters:
      - description: Set of users
        in: path
        name: set
<<<<<<< HEAD
        required: true
=======
>>>>>>> 9e910e6 (Implementing endpoint structure)
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/users.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.User'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/users.ResponseHTTP'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/users.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/users.ResponseHTTP'
      summary: Get set of all users
      tags:
      - users
schemes:
- http
swagger: "2.0"
