basePath: /
definitions:
  models.Err:
    properties:
      description:
        description: the error description for the developer, aka err.Error()
        type: string
      message:
        description: the displayed error text for the user
        type: string
      name:
        type: string
      status:
        type: integer
    type: object
  models.Post:
    properties:
      birdId:
        type: string
      createdAt:
        type: string
      id:
        type: string
      imageId:
        type: string
      location:
        type: string
      soundId:
        type: string
      userId:
        type: string
    type: object
  models.Response:
    properties:
      data: {}
      timestamp:
        type: string
    type: object
  models.ResponseHTTP:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  models.User:
    properties:
      _id:
        type: string
      active:
        type: boolean
      authId:
        type: string
      createdAt:
        type: string
      username:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: ??
    name: Tovah Parnes
  description: A server for BirdAI API, for managing users, admin, birds, posts and
    more.
  license:
    name: MIT License
    url: https://opensource.org/license/mit/
  termsOfService: http://swagger.io/terms/
  title: BirdAI API
  version: "2.0"
paths:
  /posts/:
    post:
      consumes:
      - application/json
      description: Create a new post
      parameters:
      - description: post
        in: body
        name: set
        required: true
        schema:
          $ref: '#/definitions/models.Post'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
      summary: Create a new post
      tags:
      - Posts
  /posts/{id}:
    delete:
      consumes:
      - application/json
      description: Delete given post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "401":
          description: Unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
        "403":
          description: Forbidden
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
      summary: Delete given post
      tags:
      - Posts
    get:
      consumes:
      - application/json
      description: Get post by ID
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Post'
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
        "410":
          description: Gone
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
      summary: Get post by ID
      tags:
      - Posts
    patch:
      consumes:
      - application/json
      description: Update given post
      parameters:
      - description: post ID
        in: path
        name: id
        required: true
        type: string
      - description: post
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.Post'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
        "403":
          description: Forbidden
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
      summary: Update given post
      tags:
      - Posts
  /posts/list:
    get:
      consumes:
      - application/json
      description: List all posts of a specified set
      parameters:
      - description: Set of posts
        in: query
        name: set
        type: integer
      - description: Search parameter for post
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Post'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
      summary: List all posts of a specified set
      tags:
      - Posts
  /users/:
    post:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: user
        in: body
        name: set
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
      summary: Create user
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete given user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
      summary: Delete given user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.User'
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "410":
          description: Gone
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
      summary: Get user by ID
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Update given user
      parameters:
      - description: user
        in: body
        name: set
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
      summary: Update given user
      tags:
      - users
  /users/{id}/posts/list:
    get:
      consumes:
      - application/json
      description: List all posts of a specified set
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Set of posts
        in: query
        name: set
        type: integer
      - description: Search parameter for post
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Post'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Err'
                  type: array
              type: object
      summary: List all posts of a specified set
      tags:
      - Posts
  /users/list:
    get:
      consumes:
      - application/json
      description: List all users of a specified set
      parameters:
      - description: Set of users
        in: query
        name: set
        type: integer
      - description: Search parameter for user
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.User'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
      summary: List all users of a specified set
      tags:
      - users
  /users/me:
    get:
      consumes:
      - application/json
      description: Get current user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "410":
          description: Gone
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
      summary: Get current user
      tags:
      - users
schemes:
- http
swagger: "2.0"
